# Cost = Initial cost of ore. (0% change)
# Value = Current cost of ore. (With % change)
# When adding a new ore make the cost and value to same

items:
  0:
    item: DIAMOND
    name: '&bDiamond Ore'
    lore:
      - '&a$1000'
    cost: 1000
    value: 1000

  1:
    item: GOLD_INGOT
    name: '&6Gold Ingot'
    lore:
      - '&a$500'
    cost: 500
    value: 500

  2:
    item: IRON_INGOT
    name: '&7Iron Ore'
    lore:
      - '&a$250'
    cost: 250
    value: 250

