name: OreMarket
version: ${project.version}
main: com.olliejw.oremarket.OreMarket
api-version: 1.16
depend: [ Vault ]
authors: [ OllieJW ]
description: Realistic stock market for ores

commands:
  openmarket:
    description: Opens OreMarket GUI
    usage: /<command>
  om-reload:
    description: Reloads OreMarket
    usage: /<command>